services:
  postgres:
    image: postgres:16-alpine
    container_name: nexusnews-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: raushan
      POSTGRES_PASSWORD: raushan21
      POSTGRES_DB: ai_news_generator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raushan -d ai_news_generator -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
